/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKYCVerification,
  IKYCVerificationInterface,
} from "../IKYCVerification";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "checkKYC",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IKYCVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IKYCVerificationInterface {
    return new utils.Interface(_abi) as IKYCVerificationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKYCVerification {
    return new Contract(address, _abi, signerOrProvider) as IKYCVerification;
  }
}
