/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  KYCVerification,
  KYCVerificationInterface,
} from "../KYCVerification";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "UserVerified",
    type: "event",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "changeAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "checkKYC",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userList",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bool",
        name: "verified",
        type: "bool",
      },
    ],
    name: "verifyUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b0319163317905561037a806100326000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c80631b4e7bd21461005c5780637e7ed032146100945780638846594b146100a95780638f283970146100d5578063f851a440146100e8575b600080fd5b61007f61006a3660046102a5565b60016020526000908152604090205460ff1681565b60405190151581526020015b60405180910390f35b6100a76100a23660046102c7565b610113565b005b61007f6100b73660046102a5565b6001600160a01b031660009081526001602052604090205460ff1690565b6100a76100e33660046102a5565b61020b565b6000546100fb906001600160a01b031681565b6040516001600160a01b03909116815260200161008b565b6000546001600160a01b031633146101465760405162461bcd60e51b815260040161013d90610303565b60405180910390fd5b6001600160a01b03821660009081526001602052604090205460ff16156101af5760405162461bcd60e51b815260206004820152601860248201527f5573657220697320616c72656164792076657269666965640000000000000000604482015260640161013d565b6001600160a01b038216600081815260016020908152604091829020805460ff191685151517905590519182527fa6625d2d26e786e2f473111bea4b2fcdbbf1863d883a2359989ce3a103d2972a910160405180910390a15050565b6000546001600160a01b031633146102355760405162461bcd60e51b815260040161013d90610303565b600080546001600160a01b0319166001600160a01b0383169081179091556040519081527f7ce7ec0b50378fb6c0186ffb5f48325f6593fcb4ca4386f21861af3129188f5c9060200160405180910390a150565b80356001600160a01b03811681146102a057600080fd5b919050565b6000602082840312156102b757600080fd5b6102c082610289565b9392505050565b600080604083850312156102da57600080fd5b6102e383610289565b9150602083013580151581146102f857600080fd5b809150509250929050565b60208082526021908201527f4f6e6c792061646d696e2063616e2063616c6c20746869732066756e6374696f6040820152603760f91b60608201526080019056fea26469706673582212200bac2fc49eb44ffb8fd526bea37f4e6e6590c760b1b5d6d972d487d4410eff1f64736f6c63430008140033";

export class KYCVerification__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<KYCVerification> {
    return super.deploy(overrides || {}) as Promise<KYCVerification>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): KYCVerification {
    return super.attach(address) as KYCVerification;
  }
  connect(signer: Signer): KYCVerification__factory {
    return super.connect(signer) as KYCVerification__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KYCVerificationInterface {
    return new utils.Interface(_abi) as KYCVerificationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KYCVerification {
    return new Contract(address, _abi, signerOrProvider) as KYCVerification;
  }
}
